name: Flask App CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Build Docker Image
      run: |
        docker build -t akanksha289/my-flask-app .

    - name: Push Docker Image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push akanksha289/my-flask-app:latest  # Push your image with a tag
